# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import analysis_gdp_pb2 as analysis__gdp__pb2


class GdpDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GdpData = channel.unary_unary(
                '/gdp.GdpDataService/GdpData',
                request_serializer=analysis__gdp__pb2.GdpDataRequest.SerializeToString,
                response_deserializer=analysis__gdp__pb2.GdpDataResponse.FromString,
                )


class GdpDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GdpData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GdpDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GdpData': grpc.unary_unary_rpc_method_handler(
                    servicer.GdpData,
                    request_deserializer=analysis__gdp__pb2.GdpDataRequest.FromString,
                    response_serializer=analysis__gdp__pb2.GdpDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gdp.GdpDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GdpDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GdpData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gdp.GdpDataService/GdpData',
            analysis__gdp__pb2.GdpDataRequest.SerializeToString,
            analysis__gdp__pb2.GdpDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
