// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: ons_gdp.proto

package gdp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GdpData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quarter string `protobuf:"bytes,1,opt,name=quarter,proto3" json:"quarter,omitempty"`
	Number  int32  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *GdpData) Reset() {
	*x = GdpData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ons_gdp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GdpData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GdpData) ProtoMessage() {}

func (x *GdpData) ProtoReflect() protoreflect.Message {
	mi := &file_ons_gdp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GdpData.ProtoReflect.Descriptor instead.
func (*GdpData) Descriptor() ([]byte, []int) {
	return file_ons_gdp_proto_rawDescGZIP(), []int{0}
}

func (x *GdpData) GetQuarter() string {
	if x != nil {
		return x.Quarter
	}
	return ""
}

func (x *GdpData) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GdpDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GdpDataRequest) Reset() {
	*x = GdpDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ons_gdp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GdpDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GdpDataRequest) ProtoMessage() {}

func (x *GdpDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ons_gdp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GdpDataRequest.ProtoReflect.Descriptor instead.
func (*GdpDataRequest) Descriptor() ([]byte, []int) {
	return file_ons_gdp_proto_rawDescGZIP(), []int{1}
}

type GdpDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*GdpData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GdpDataResponse) Reset() {
	*x = GdpDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ons_gdp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GdpDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GdpDataResponse) ProtoMessage() {}

func (x *GdpDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ons_gdp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GdpDataResponse.ProtoReflect.Descriptor instead.
func (*GdpDataResponse) Descriptor() ([]byte, []int) {
	return file_ons_gdp_proto_rawDescGZIP(), []int{2}
}

func (x *GdpDataResponse) GetData() []*GdpData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_ons_gdp_proto protoreflect.FileDescriptor

var file_ons_gdp_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6f, 0x6e, 0x73, 0x5f, 0x67, 0x64, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6f, 0x6e, 0x73, 0x5f, 0x67, 0x64, 0x70, 0x22, 0x3b, 0x0a, 0x07, 0x47, 0x64, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x61, 0x72, 0x74, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x61, 0x72, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x64, 0x70, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x0f, 0x47, 0x64, 0x70, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x6e, 0x73, 0x5f, 0x67,
	0x64, 0x70, 0x2e, 0x47, 0x64, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x32, 0x4e, 0x0a, 0x0e, 0x47, 0x64, 0x70, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x47, 0x64, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x17, 0x2e,
	0x6f, 0x6e, 0x73, 0x5f, 0x67, 0x64, 0x70, 0x2e, 0x47, 0x64, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6f, 0x6e, 0x73, 0x5f, 0x67, 0x64, 0x70,
	0x2e, 0x47, 0x64, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0c, 0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x64, 0x70, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ons_gdp_proto_rawDescOnce sync.Once
	file_ons_gdp_proto_rawDescData = file_ons_gdp_proto_rawDesc
)

func file_ons_gdp_proto_rawDescGZIP() []byte {
	file_ons_gdp_proto_rawDescOnce.Do(func() {
		file_ons_gdp_proto_rawDescData = protoimpl.X.CompressGZIP(file_ons_gdp_proto_rawDescData)
	})
	return file_ons_gdp_proto_rawDescData
}

var file_ons_gdp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ons_gdp_proto_goTypes = []interface{}{
	(*GdpData)(nil),         // 0: ons_gdp.GdpData
	(*GdpDataRequest)(nil),  // 1: ons_gdp.GdpDataRequest
	(*GdpDataResponse)(nil), // 2: ons_gdp.GdpDataResponse
}
var file_ons_gdp_proto_depIdxs = []int32{
	0, // 0: ons_gdp.GdpDataResponse.data:type_name -> ons_gdp.GdpData
	1, // 1: ons_gdp.GdpDataService.GdpData:input_type -> ons_gdp.GdpDataRequest
	2, // 2: ons_gdp.GdpDataService.GdpData:output_type -> ons_gdp.GdpDataResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ons_gdp_proto_init() }
func file_ons_gdp_proto_init() {
	if File_ons_gdp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ons_gdp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GdpData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ons_gdp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GdpDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ons_gdp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GdpDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ons_gdp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ons_gdp_proto_goTypes,
		DependencyIndexes: file_ons_gdp_proto_depIdxs,
		MessageInfos:      file_ons_gdp_proto_msgTypes,
	}.Build()
	File_ons_gdp_proto = out.File
	file_ons_gdp_proto_rawDesc = nil
	file_ons_gdp_proto_goTypes = nil
	file_ons_gdp_proto_depIdxs = nil
}
