# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analysis_gdp.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61nalysis_gdp.proto\x12\x03gdp\"*\n\x07GdpData\x12\x0f\n\x07quarter\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\x05\"\x10\n\x0eGdpDataRequest\"-\n\x0fGdpDataResponse\x12\x1a\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0c.gdp.GdpData2F\n\x0eGdpDataService\x12\x34\n\x07GdpData\x12\x13.gdp.GdpDataRequest\x1a\x14.gdp.GdpDataResponseB\x0cZ\nprotos/gdpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_gdp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\nprotos/gdp'
  _globals['_GDPDATA']._serialized_start=27
  _globals['_GDPDATA']._serialized_end=69
  _globals['_GDPDATAREQUEST']._serialized_start=71
  _globals['_GDPDATAREQUEST']._serialized_end=87
  _globals['_GDPDATARESPONSE']._serialized_start=89
  _globals['_GDPDATARESPONSE']._serialized_end=134
  _globals['_GDPDATASERVICE']._serialized_start=136
  _globals['_GDPDATASERVICE']._serialized_end=206
# @@protoc_insertion_point(module_scope)
