// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: ons_gdp.proto

package gdp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GdpDataServiceClient is the client API for GdpDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GdpDataServiceClient interface {
	GdpData(ctx context.Context, in *GdpDataRequest, opts ...grpc.CallOption) (*GdpDataResponse, error)
}

type gdpDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGdpDataServiceClient(cc grpc.ClientConnInterface) GdpDataServiceClient {
	return &gdpDataServiceClient{cc}
}

func (c *gdpDataServiceClient) GdpData(ctx context.Context, in *GdpDataRequest, opts ...grpc.CallOption) (*GdpDataResponse, error) {
	out := new(GdpDataResponse)
	err := c.cc.Invoke(ctx, "/ons_gdp.GdpDataService/GdpData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GdpDataServiceServer is the server API for GdpDataService service.
// All implementations must embed UnimplementedGdpDataServiceServer
// for forward compatibility
type GdpDataServiceServer interface {
	GdpData(context.Context, *GdpDataRequest) (*GdpDataResponse, error)
	mustEmbedUnimplementedGdpDataServiceServer()
}

// UnimplementedGdpDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGdpDataServiceServer struct {
}

func (UnimplementedGdpDataServiceServer) GdpData(context.Context, *GdpDataRequest) (*GdpDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GdpData not implemented")
}
func (UnimplementedGdpDataServiceServer) mustEmbedUnimplementedGdpDataServiceServer() {}

// UnsafeGdpDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GdpDataServiceServer will
// result in compilation errors.
type UnsafeGdpDataServiceServer interface {
	mustEmbedUnimplementedGdpDataServiceServer()
}

func RegisterGdpDataServiceServer(s grpc.ServiceRegistrar, srv GdpDataServiceServer) {
	s.RegisterService(&GdpDataService_ServiceDesc, srv)
}

func _GdpDataService_GdpData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GdpDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GdpDataServiceServer).GdpData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ons_gdp.GdpDataService/GdpData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GdpDataServiceServer).GdpData(ctx, req.(*GdpDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GdpDataService_ServiceDesc is the grpc.ServiceDesc for GdpDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GdpDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ons_gdp.GdpDataService",
	HandlerType: (*GdpDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GdpData",
			Handler:    _GdpDataService_GdpData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ons_gdp.proto",
}
