name: ec2-push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy to ec2 on push to master
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          SCRIPT_BEFORE: |
            sudo systemctl stop apache2
            cd /home/ubuntu/home/
            rm -rf *
          SCRIPT_AFTER: |
            cd /home/ubuntu/home/scripts
            chmod +x deploy.sh
            sudo bash deploy.sh
